"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
# truncation_length = 3

[git_branch]
symbol = ''

[git_status]
stashed = ''
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'

[aws]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true